### ISSUE TITLE
[Feature] Allow mobile client to perform actions on selected items 

### ISSUE THREAD

**Issue by MarcusB416** [oxen-io/session-ios#1051]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

on the desktop client , you can select and perform actions in a batch format. (delete, etc.).

This would be a nice feature for the iOS client.

**Comment by pottsandpans** [comment]
Closing as duplicate of: https://github.com/oxen-io/session-ios/issues/468
