### ISSUE TITLE
[BUG] Disappearing message timer not set when sharing from other App

### ISSUE THREAD

**Issue by ChrisEgger76** [oxen-io/session-ios#1054]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Message timer between both parties is set to 5 minutes after read. Messages sent from Session messenger disappear as expected but when sharing from another app e.g. Photos app or a Safari link using the apps share function no timer is set on the messages.

### Expected Behavior

expected behavior is that all messages in a conversation where disappearing messages are configured are deleted from both parties within the set timeframe.

### Steps To Reproduce

open a website in safari browser
use the share function of safari and select "Session messenger"
select a contact where an exisiting chat conversation is configured with disapperaing messages set to 5 minutes after read.
click "Send"
after that open the session app 
no timer symbol is shown next to the message
when tapping on the message for a second in the dropdown menu there is also no time in minutes and seconds shown next to the "delete" entry

### iOS Version

iOS 18.1.1

### Session Version

2.8.3 (507 -3931de8)

**Comment by LuLuLoLu** [comment]
Tracked internally with SES-3086

**Comment by mpretty-cyro** [comment]
This should be fixed by https://github.com/session-foundation/session-ios/pull/347 (included in `2.8.4` - https://github.com/session-foundation/session-ios/pull/350)

**Comment by KeeJef** [comment]
Closing this for now, please reopen in the [Session Foundation iOS repo](https://github.com/session-foundation/session-ios/issues) if the issue persists after the update
