### ISSUE TITLE
Support iPad

### ISSUE THREAD

**Issue by KeeJef** [oxen-io/session-ios#109]
Theres quite a few users who want to use Session on their iPad, we should add support for iPads

**Comment by malicioustoker** [comment]
Are we ever going to get support for iPadOS?

**Comment by KeeJef** [comment]
Its not a priority at the moment, but we will get to it

**Comment by RyanRory** [comment]
We are supporting iPad now, and we just added support for iPad landscape mode with our latest release (2.2.3).
