### ISSUE TITLE
Image rotation is reversed

### ISSUE THREAD

**Issue by james-culp** [oxen-io/session-ios#207]
**Describe the bug**

When I shoot a picture in Session and want to rotate it before sending, the button clearly indicates **counter-clockwise** rotation, but it works in a **clockwise** fashion.

**To reproduce**

1. In a conversation, hit the plus button and select "camera"
2. Take a picture
3. On the edit screen before sending, hit the crop button in the top right
4. Hit the rotate button in the lower left. The arrow indicates counter-clockwise
5. Image is rotated clockwise

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro
 - OS: iOS 13.5
 - Version of Session: 1.2.3

**Additional context**

**Comment by GodGoldfish** [comment]
this issue is still happening in Session 1.12.1, this is quite useless to have this button if it does the same as the one just aside.

**Comment by RyanRory** [comment]
Hi @james-culp @GodGoldfish , happy to report this has been fixed in our latest release (1.11.21). Cheers!
