### ISSUE TITLE
Error sending video longer than 9 seconds

### ISSUE THREAD

**Issue by Jason-Winters123** [oxen-io/session-ios#304]
**Describe the bug**

Error sending video longer than 9 seconds, when it used to send significantly more

**To reproduce**

Steps to reproduce the behavior: Record or send video greater than 9 seconds in length. Error message gets displayed saying 'attachment is too large' and media is not sent.

**Screenshots or logs**

![image](https://user-images.githubusercontent.com/73737504/97775070-64aa8900-1b55-11eb-9e9d-d465b4ac0457.png)

**Smartphone (please complete the following information):**

 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS 14.0.1]
 - Version of Session or latest commit hash [Version 1.6.3]

**Additional context**

Used to send 30+ second videos or media with no problem. Now says 9 seconds in too large, and sometimes even less too.

**Comment by Jason-Winters123** [comment]
I am sure this bug will be fixed soon enough, just thought I'd come back to update on how it has evolved over time...

Recently I have noticed that the video length 'limit' has dropped even lower for me... from 9 seconds now to anything below 5. I have also noticed that I CAN send multiple videos, each below 5 seconds but cumulatively well above, as well as videos straight from my photo library which exceed 5 seconds in length. So for some reason, it is just the videos captured within the app which seems to be the problem.

Btw, kudos to the devs for being so active in this community, it's really refreshing to see!

![IMG_4403](https://user-images.githubusercontent.com/73737504/106315707-8f46d380-6263-11eb-8663-0e5df7837fef.PNG)

**Comment by GodGoldfish** [comment]
This issue is still happening on iOS 15.2.1 and session 1.12.1, it only happens when you use the built-in camera integration of session, sending video recorded with an external source doesn't make this to happen, the title of this issue is confusing i suggest "Error recording video longer than 9 seconds".

**Comment by KeeJef** [comment]
i don't think this has to do with the length of the video, you are probably just bumping into the max file size limits for the file server. Just tested in the latest version of Session If a video file exceeds this limit, it fails to upload silently, which needs to be addressed. 

We should consider applying video compression in the app to reduce file sizes, disabling the feature altogether or limiting the length of recorded videos to prevent confusion and frustration for users. @mpretty-cyro , can you confirm if we are already applying video compression to videos recorded the app?

**Comment by mpretty-cyro** [comment]
> @mpretty-cyro , can you confirm if we are already applying video compression to videos recorded the app?

Nope, we do re-encode videos coming in from external sources but looking at the code it seems like it's mostly to standardise the file type between the different clients (to `mp4`)

Recording a video directly in the app starts as an `mp4` so doesn't go through any processing. It does look like the system we use for video recording has `maxRecordedDuration` and `maxRecordedFileSize` settings so we could potentially limit it that way to help mitigate this bad UX?

**Comment by KeeJef** [comment]
Yeah probably capping on maxRecordedFileSize, and when its exceeded we stop the video and tell the user, is the best way to go for now

**Comment by KeeJef** [comment]
This should now be resolved, video will stop recording and allow user to send when file size limitation is reached
