### ISSUE TITLE
Message not being displayed

### ISSUE THREAD

**Issue by whysyed** [oxen-io/session-ios#323]
**Describe the bug**

Session doesn't display messages when the message notification is clicked. The notification takes the user directly to the private conversation where the latest message doesn't appear until the user presses the back button to move to the main list of Session messages. 

**To reproduce**

1. Click on the message notification from the Home Screen
2. App is launched & the conversation is loaded but the latest message doesn't appear

**Smartphone (please complete the following information):**

 - Device: iPhone X
 - OS: 14.3
 - Version of Session or latest commit hash: 1.7.3 (158)

**Additional context**

The app is using the Fast Mode Notifications.

**Comment by nielsandriesse** [comment]
This should now be fixed
