### ISSUE TITLE
Desktop and Mobile chats not syncing 

### ISSUE THREAD

**Issue by LeonardoMaracino** [oxen-io/session-ios#327]
I send messages with my iPhone and have a chat with a friend.
When I go and open the same conversation with macOS, it only shows messages sent by the other person to me, but not the ones I sent.

**To reproduce**

I send and receive messages with iOS.
Then I go and open the same conversation on macOS version.

<img width="992" alt="macOS Session" src="https://user-images.githubusercontent.com/57290045/104105221-f993d600-52ac-11eb-875c-f8dceddf46d2.png">

![iOS Session](https://user-images.githubusercontent.com/57290045/104105224-fbf63000-52ac-11eb-9909-4c322582a912.jpeg)

 - iPhone SE
 - iOS 14.4
 - Version of Session 1.7.3 (158)
  
  
- MacBook Pro M1 2020
- macOS 11.1
- Version of Session 1.4.4

**Comment by nielsandriesse** [comment]
Multi device is only now being released. Up until this point it wasn't an officially supported feature.
