### ISSUE TITLE
Cannot playback sent audio message

### ISSUE THREAD

**Issue by Vijay-Duke** [oxen-io/session-ios#329]
**Describe the bug**
When I send an audio recording, I cannot play back the message which was sent.

**To reproduce**
Open session app on iphone 12 (ios 14)
Send a audio recording message to someone
Click on the audio message to hear message sent. It'll not playback

**Screenshots or logs**
N/A

**Smartphone (please complete the following information):**

 - Device: [iphone 12 pro max]
 - OS: [ios 14]
 - version: latest available on apple store as of 09/01/2021

**Comment by nielsandriesse** [comment]
This can happen when your device is muted. A fix will be included in the next release!

**Comment by LeonardoMaracino** [comment]
> This can happen when your device is muted. A fix will be included in the next release!

That's correct. I noticed that too.
Keep up the good work!
