### ISSUE TITLE
Messages are not displayed since 1.7.4 update in iOS and Windows App 1.4.5 if coming from an older session version

### ISSUE THREAD

**Issue by xtlc** [oxen-io/session-ios#336]
Since the last update (1.7.4) I only see the notifications of the messages arriving, but when opening the app I cannot see the message beneath the contacts' name where usually a few words of the last message are visible. Also when choosing the conversation actively in the app, I cannot see messages from 1.7.4.. They are also not arriving on my desktop client (but here I also cannot see notifications).

* iOS 14.3
* iPhone 7
* Session 1.7.4 (iOS)
* Windows 10
* Session 1.4.5 (Win desktop app)

I would guess this is not a problem purely of the client, but maybe the protocol, but I decided to post here because I do get notifications under iOS but not the message. 

Edit:
I tinkered a little bit with my second phone and found out I had to update it as well, but never got an error message on messages which were not received.

**Comment by nielsandriesse** [comment]
This isn't a bug. The last update was a mandatory one :) .

**Comment by xtlc** [comment]
When I get a notification on my home screen but cannot open the message after that, there is at least a bug in the displaying. Also it would come in handy for the sender to see that the receiver will not be able to see the message. This is why I still left the ticket open after my Edit.
