### ISSUE TITLE
forced session id update on 1.7.7

### ISSUE THREAD

**Issue by InoMurko** [oxen-io/session-ios#348]
**Describe the bug**

My iOS app updated two days ago to 1.7.7.
Today I was forced to *update session id* to a new one by which I lost all my contacts and messages.
My previous session id was at most two weeks old.

**To reproduce**

No idea.

**Screenshots or logs**

**Smartphone (please complete the following information):**

 - iphone 12 mini
 - OS: 14.4
 - 1.7.7

**Additional context**

**Comment by InoMurko** [comment]
![20210205_122308000_iOS](https://user-images.githubusercontent.com/2582555/107033627-e134af80-67b5-11eb-8267-9d0a924dbe48.png)
![20210205_122449000_iOS](https://user-images.githubusercontent.com/2582555/107033645-e691fa00-67b5-11eb-974f-48af7863796d.png)


Happened again today. After I pressed upgrade later I've lost all messages, conversations and contacts.

**Comment by InoMurko** [comment]
I can't get pass the "white screen of Oxcen" and I presume I'll need to re-install the app.

**Comment by InoMurko** [comment]
After Iphone restart, all conversations came back, no new "upgrade session id" notification. Weird!

**Comment by nielsandriesse** [comment]
We now no longer force show this modal, so this issue shouldn't happen anymore :)
