### ISSUE TITLE
Face ID Block not working

### ISSUE THREAD

**Issue by LorisTecnology** [oxen-io/session-ios#353]
**Describe the bug**

I've seen this issue on my MI A2 but turned out that happen also on Ios 
When Face ID block is enabled it doesn't work even the first tiime

Android Issue
https://github.com/oxen-io/session-android/issues/448

**To reproduce**

1. Open Session
2. Enable the Face ID block
3. Close Session
4. Face ID doesn't work

**Smartphone (please complete the following information):**

 - Device: Iphone 11

**Comment by nielsandriesse** [comment]
You need to set the screen lock timeout to instant (below the screen lock toggle in the settings) if you want Session to lock immediately after you closed it.

**Comment by LorisTecnology** [comment]
i've did this
and nothing changed
