### ISSUE TITLE
iOS Session doesn't always show full message

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#367]
**Describe the bug**

iOS doesn't always show the full message, some words at the end is cut.
Happens only in closed group, haven't seen this behaviour in Open Groups or 1-1 chats.

**Screenshots or logs**
iOS
After the message "Heh", in the two following messages last word/words in sentence is missing. Sorry that the discussion is in Finnish, but important is you see the point.
![20210315_065529000_iOS](https://user-images.githubusercontent.com/77722427/111124148-d6212c00-8578-11eb-9cd7-6cfdbb9749fe.png)

Desktop
<img width="826" alt="Screenshot 2021-03-15 at 8 55 44" src="https://user-images.githubusercontent.com/77722427/111124325-11235f80-8579-11eb-8d97-84fe92fc088e.png">

**Smartphone (please complete the following information):**

 - Device: iPhone 11 (happens on other iOS devices too)
 - OS: 14.4 (don't know version on other iOS devices)
 - Version of Session: 1.9.1 (206)

**Comment by Marky-N** [comment]
Proof of iOS not showing full message, even within iOS. So when replying it shows the full message but not in the chat itself.
![20210321_190724000_iOS](https://user-images.githubusercontent.com/77722427/111917709-21ac6c00-8a8a-11eb-9a05-dbe16ae1b789.png)

**Comment by nielsandriesse** [comment]
This has been fixed in #374
