### ISSUE TITLE
DM with 99+ unread -> Session closes itself

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#368]
**Describe the bug**

When using multi-device, all messages are not read on all the devices at the same time. In my case, I mainly use my iPhone but also have Session installed on iPad. When a DM shows over 99+ unread messages and you try to open that chat, Session quits itself directly. This means that it's not possible to use that chat anymore from that device.

**To reproduce**

Use Multi-device. Have over 100 message unread in a 1-1 conversation, open chat with iOS closes Session.

**Smartphone (please complete the following information):**

 - Device: iPhone 11; iPad Pro 10,5"
 - OS: iOS 14.4; iOS 14.4
 - Version of Session: 1.9.1 (206); 1.9.1 (206)

**Comment by Marky-N** [comment]
This actually also happens with closed groups.

**Comment by nielsandriesse** [comment]
This should be fixed now :)

**Comment by Marky-N** [comment]
@nielsandriesse My friend has newest softwares iOS and Session (updated today), still has issues with this. Force close when he tries to open closed group that shows 99+ unread messages.
