### ISSUE TITLE
UX glitchy, lagging when typing

### ISSUE THREAD

**Issue by InoMurko** [oxen-io/session-ios#371]
**Describe the bug**

When typing, keyboard strokes appear glitchy and lagging, like the CPU can't handle typing.
Sometimes sent messages stay in the messagebox before they're actually sent.
Messages are delivered several hours late. I also receive messages with delays of several hours.
 
**To reproduce**

1:1 messaging, no groups joined at all.

**Screenshots or logs**

/

**Smartphone (please complete the following information):**

 - Device: iphone 12 mini
 - OS: 14.4
 - 1.9.1 206

**Additional context**

/

**Comment by nielsandriesse** [comment]
This should now be fixed

**Comment by InoMurko** [comment]
True! Thanks!
