### ISSUE TITLE
Muting closed groups

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#382]
**Describe the bug**

On Session it's possible to mute groups, but it seems it's not possible on closed groups, works only on Open Groups

**To reproduce**

Try to mute a closed group through the settings on Session. Ask someone to send a message to the group.

**Smartphone:**

 - Device: iPhone
 - OS: 14.4.2
 - Version of Session: 1.9.5

**Comment by coo1k** [comment]
I’m not able to reproduce this issue. @Marky-N have you tried on latest version?

I created a closed group, muted it and sent message from other device. I did not get notifications.
Then I unmuted the group and I got notifications.

**Comment by Marky-N** [comment]
Need to check

**Comment by Marky-N** [comment]
Confirmed this works now.
