### ISSUE TITLE
messages not delivered, delivered but unordered, random push notifications 

### ISSUE THREAD

**Issue by InoMurko** [oxen-io/session-ios#385]
Session has basically become completely unreliable over the past few weeks.

- Conversations appear unread and can't mark them as read
- Conversations randomly inserting missing messages in the conversation history
- Random push notifications for days old messages that I can't see or read anymore
- Messages don't get delivered immediately but they arrive hours or days later
- Messages don't get received in the thread, but arrive unordered

**Comment by M09NST3R** [comment]
Yeah, these things make Session appear unreliable. When I send a message on Session, I still see it as "best effort" delivery. I sometimes ask my counterparties on some other app if they've received my Session messages or not. Usually they get it at some point, but when is not always predictable.

This needs to improve.

**Comment by RyanRory** [comment]
We've got multiple reports of delays in receiving messages, and we are working hard on fixing it. I'll close this issue for now. And we can move the discussion to #566. Cheers!
