### ISSUE TITLE
ONS doesn't work after Service Node 9.1 taken into use

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#397]
**Describe the bug**

After the hardfork of the service nodes and the software taken into use on the network, the ONS names don't work. This has been also tried by using own ONS name for "Note to myself" as well as trying to message someone through ONS name.

![20210430_085822000_iOS](https://user-images.githubusercontent.com/77722427/116676771-106f4d00-a9b0-11eb-9cfc-a72d6d4c03ed.jpg)

**Smartphone (please complete the following information):**

 - Device: iPhone 11
 - OS: iOS 14.5
 - Version of Session 1.9.7

**Comment by nielsandriesse** [comment]
This should be fixed with the coming update (1.10.0)
