### ISSUE TITLE
Sending messages fails after being idle with new 9.1 Service Node network

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#398]
**Describe the bug**

When opening up Session after phone being idle and screen dark for some time, push notifications are coming to the phone from Session but not able to send messages. Resending doesn't work.

![20210430_095516000_iOS](https://user-images.githubusercontent.com/77722427/116679850-ac4e8800-a9b3-11eb-896b-18e6063fd17c.jpg)

The problem appeared today after the hardfork of the Service Nodes. Somehow the path "gets stuck".

**To reproduce**

Have phone with Session open and turn off the screen at let it be turned off for 5 minutes (maybe). Someone sends a message to a group or 1-1, click on notification. When replying it thinks a long time until the error message appears.
Workaround, close Session and restart it, go to Path and see that it finds new SN and a new path. The messages will be sent then.

**Smartphone (please complete the following information):**

 - Device: iPhone 11
 - OS: iOS 14.5
 - Version of Session 1.9.7

**Comment by nielsandriesse** [comment]
This should be fixed with the coming update (1.10.0)
