### ISSUE TITLE
Groups don't appear on iPhones after ID has been added

### ISSUE THREAD

**Issue by Norbert80** [oxen-io/session-ios#399]
If I (Android) add members who use iPhone to my private group they do not see the group!

I use Android build: v1.9.1

**Comment by nielsandriesse** [comment]
This is more likely an Android issue than an iOS one

**Comment by Norbert80** [comment]
Hi @nielsandriesse

In fact this would be really strange since the groups appear an Android and Desktop clients as well.

However, in case you are right it might be the best approach to investigate on iPhone side what happens.

**Comment by nielsandriesse** [comment]
Hi @Norbert80, I believe we've figured out the issue. Stay tuned for updates that fix it :) .

**Comment by Norbert80** [comment]
@nielsandriesse sounds great. Thanks!

**Comment by nielsandriesse** [comment]
If you recreate your closed groups and ensure that all members are on the latest version of Session this should now be fixed!

**Comment by twinboi90** [comment]
I am having the same issue
