### ISSUE TITLE
sharing website is shared as a attachment file

### ISSUE THREAD

**Issue by InoMurko** [oxen-io/session-ios#407]
After version 1.10.2 was introduced, if you Safari -> Share -> Session contact it's shared as a file attachement.

**Comment by InoMurko** [comment]
<img width="201" alt="Screenshot 2021-06-09 at 14 52 46" src="https://user-images.githubusercontent.com/2582555/121357804-5fef5400-c932-11eb-997b-e02b1721290d.png">
<img width="312" alt="Screenshot 2021-06-09 at 14 52 33" src="https://user-images.githubusercontent.com/2582555/121357808-61208100-c932-11eb-81fc-93cad74a0f0b.png">

**Comment by InoMurko** [comment]
1.11.5 still around

**Comment by RyanRory** [comment]
Hi @InoMurko, thanks for reporting this issue. The entire 'Sharing to Session' is not working so well. We are working on fixing this. Since this issue is part of #528, I'll close it for now. You can continue report and discuss issues under #528. Cheers :)
