### ISSUE TITLE
Crash when delete images in the first time

### ISSUE THREAD

**Issue by Pingmin** [oxen-io/session-ios#409]
**Describe the bug**

Session exits when delete image files at the first time, but then it is OK to delete images after relaunch.

**To reproduce**

Steps to reproduce the behavior.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone SE
 - OS: iOS 14.5
 - Version of Session: v1.10.2 (236)

**Additional context**

**Comment by GodGoldfish** [comment]
This issue can be closed, i tried and this no longer happens on the last version of iOS 15.2.1 and session 1.12.1

**Comment by Pingmin** [comment]
But I still get some crash in my device with the latest iOS and Session at present(e.g.: On last Sunday, 20220116).

**Comment by RyanRory** [comment]
Hi @Pingmin, could you please provide us more detail for the crash? Like the steps to reproduce this issue. Cheers!

**Comment by RyanRory** [comment]
Seems like this issue no longer exists. Will close this for now. :)
