### ISSUE TITLE
Locked Session displays enum value

### ISSUE THREAD

**Issue by phatina** [oxen-io/session-ios#413]
**Describe the bug**

SCREEN_LOCK_REASON_UNLOCK_SCREEN_LOCK is displayed when unknown face is presented to a locked Session. 

**To reproduce**

Enable locking Session and faceid. Try to unlock Session with face not known to the phone. Most likely an enum string is displayed. 

**Screenshots or logs**

![B9187651-E036-49E0-BF22-9FA3BDFB4C53](https://user-images.githubusercontent.com/1381504/118848013-a4a54380-b8ce-11eb-9314-c38809821098.png)

**Smartphone**

 - Device: iPhone 12 mini
 - OS: iOS 14.5
 - Version of Session 1.10.2 (236)

**Comment by nielsandriesse** [comment]
This is fixed; scheduled to go out with 1.11.1 :)
