### ISSUE TITLE
Attaching camera photo crashes the app

### ISSUE THREAD

**Issue by phatina** [oxen-io/session-ios#414]
**Describe the bug**

Trying to attach a freshly taken photo to a group conversation crashes the app. 

**To reproduce**
Hit the plus button, select camera, take a photo. Then the app crashes. 

**Smartphone**

 - Device: iPhone 12 mini
 - OS: iOS 14.5
 - Version of Session 1.10.2 (236)

**Comment by nielsandriesse** [comment]
Hi @phatina, could you check if this still happens on the latest version of Session (1.11.3)?

**Comment by phatina** [comment]
Hi, I needed to reset Photo access (selected photos -> all photos -> selected photos) and then it works again on 1.11.3.
