### ISSUE TITLE
App link: Overlapped text in create DM window

### ISSUE THREAD

**Issue by coo1k** [oxen-io/session-ios#426]
**Code of conduct**

- [x ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
This is related to a recent change to support App links.
The sessionID in the Create DM textfield is overlapped with the placeholder of the textfield.

Steps to reproduce the behavior.
1. Open a create DM link i.e. sessionmessenger://DM?{Session ID}
2. Session App should open
3. Create DM window should automatically pop up
4. Session ID gets automatically added in the textfield.
5. The copied Session ID is overlapped with the placeholder text. So the initial part of the copied Session ID is illegible.

**Screenshots or logs**
![bug](https://user-images.githubusercontent.com/4363135/120713038-3d62c400-c476-11eb-948c-168b16963886.png)

**Smartphone (please complete the following information):**

 - Device: iPhone 11, 12 Max Pro
 - OS: 14.5
 - Version of Session or latest commit hash - Dev branch: 711006dd10f420023cdd0b60ade838f1b64a1033

**Additional context**

Introduced due to https://github.com/oxen-io/session-ios/pull/424

I believe this is caused by following line.
https://github.com/oxen-io/session-ios/blob/f4d63ba48e6d5c4425ca856edc7cc37b351c8dcc/Session/DMs/NewDMVC.swift#L277

If we replace above with below line, then issue is not seen.
`publicKeyTextView.insertText(sessionID);`

**Comment by nielsandriesse** [comment]
Ooops, that's my bad. Will make the change @coo1k :)

**Comment by nielsandriesse** [comment]
Fixed on dev.

**Comment by coo1k** [comment]
Thanks!
