### ISSUE TITLE
Session stuck at 'Optimising database'

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#432]
**Describe the bug**

When starting Session, it goes into 'Optimising database', but crashes during "optimising". Seems to somehow be a corrupted database.

**To reproduce**

New type closed group:
1) Removed an account from the closed group
2) Added person back to the group
3) When sending a message to the group for the person to see the group, Session crashed
4) After crash, optimising database is only thing seen and during that it will crash.

**Screenshots or logs**

![20210623_070731000_iOS](https://user-images.githubusercontent.com/77722427/123055599-c08c8f80-d40e-11eb-9abe-c5a6dd0df4e5.png)

**Smartphone (please complete the following information):**

 - Device: iPhone 11
 - OS: iOS 14.6
 - Session 1.11.5

**Comment by KeeJef** [comment]
Closing this for now, most migrations should now be completed since, reopen if you are still having issues with this
