### ISSUE TITLE
Notification after sending a message in closed group

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#433]
**Describe the bug**

You are getting a notification when sending message in private group on iOS.

**To reproduce**

1. Create a closed/private group.
2. Send a message.

**Screenshots or logs**

[video](https://streamable.com/m6cka0)

**Smartphone (please complete the following information):**

 - Device: iPhone 12
 - OS: iOS 14.6
 - Version of Session: 1.11.5 (257)

**Comment by Marky-N** [comment]
This is the same also for 1-1 messaging, at least for me. Only posting in open groups won't give that annoying unnecessary notification.

**Comment by nielsandriesse** [comment]
Hi @144, this is a known issue. We're working on fixing it :) .

**Comment by 144** [comment]
> 
> 
> Hi @144, this is a known issue. We're working on fixing it :) .

All right, I appreciate that.

**Comment by nielsandriesse** [comment]
We fixed this now! It'll be shipped with the next update.

**Comment by 144** [comment]
> 
> 
> We fixed this now! It'll be shipped with the next update.

Thank you very much :)
