### ISSUE TITLE
'QR codes scan permission' has no "translation"

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#435]
**Describe the bug**

Message about "QR code scanning permission" has no "translation" (is just a plain function).

**To reproduce**

"Join Open Group" -> "Scan QR Code" -> "Grant Camera Access"

**Screenshots or logs**

![image](https://i.imgur.com/zTYaxsp.jpeg)

**Smartphone (please complete the following information):**

 - Device: iPhone 12
 - OS: iOS 14.6
 - Version of Session: 1.11.5 (257)

**Comment by RyanRory** [comment]
Happy to report this is fixed in version 1.11.16. :)
