### ISSUE TITLE
'Disappearing message' doesn't work under specific circumstances

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#438]
**Describe the bug**

Sending disappearing message from Desktop app and then opening Session on iOS results in message not being 'disappearing', it has clock icon however its not updating nor disappearing after set time (tested on 1 minute disappearing message).

**To reproduce**

Link Desktop Session App -> Set Message Timer on iOS(setting on Desktop results in expiration timer not even showing on iOS) -> Close iOS App ->  Send message -> Open iOS App

**Screenshots or logs**

1. [Desktop](https://i.imgur.com/AaSaKVU.png) | [iOS](https://i.imgur.com/UFduy0z.jpeg)
2. [Desktop](https://i.imgur.com/MIhdHCu.png) | [iOS](https://i.imgur.com/sEfzcuS.jpeg)

**Smartphone (please complete the following information):**

 - Device: iPhone 12
 - OS: iOS 14.6
 - Version of Session: 1.11.5 (257) | Desktop: 1.6.6

**Comment by RyanRory** [comment]
Hi @144 Could you check if this still happens on version 1.11.16?

**Comment by 144** [comment]
> 
> 
> Hi @144 Could you check if this still happens on version 1.11.16?

Yes, it does.

**Comment by RyanRory** [comment]
Alright, thanks. We fixed a bug that could cause this, but it seems like it's a two part bug then :)

**Comment by RyanRory** [comment]
Hi @144 This issue should be fixed in our latest version. I'll close this for now. Cheers! :)
