### ISSUE TITLE
You can't set nickname to 'Anonymous' person

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#439]
**Describe the bug**

Setting a nickname to a person that never talked to you is impossible on iOS (you can do that on Desktop).

**To reproduce**

Open a chat with random person you never talked to -> Try to set a nickname

**Smartphone (please complete the following information):**

 - Device: iPhone 12
 - OS: iOS 14.6
 - Version of Session: 1.11.5 (257)

**Comment by RyanRory** [comment]
Hi @144 , this issue should be fixed in the latest version (1.11.20). Thanks for reporting this to us. :)
