### ISSUE TITLE
"x took a screenshot" is inaccurate

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#441]
**Describe the bug**

Taking a screenshot for example in. Note to Self shows in your last message recipient chat.
Also it often shows 2 times, even tho 1 screenshot was taken.

**To reproduce**

Send messages to some person -> Go to "Note to Self" and take a screenshot there
Person you was previously messaging to will see "(your nickname) took a screenshot"

**Smartphone:**

 - Device: iPhone 12
 - OS: iOS 14.6
 - Version of Session: 1.11.5 (257)

**Comment by nielsandriesse** [comment]
We're removing screenshot notifications as Android and desktop don't support it very well. We're keeping media saved notifications though.

**Comment by gianza** [comment]
Could this one stay as a feature request, instead of closed?
