### ISSUE TITLE
Suggestion: Show timestamp next to the message

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#442]
Would be nice if Session was showing timestamp next to the message like it does on Desktop app.

![image](https://i.imgur.com/wUzVrqU.png)

It looks very blank and telling when exactly was message sent is impossible. You only see that it was "Today".

**Comment by nielsandriesse** [comment]
You can reveal the timestamp by long pressing the message. We don't want to add it back into the message bubble because it clutters up the design and the precise timestamp is rarely relevant :) .
