### ISSUE TITLE
Client leaks users languages and os informations

### ISSUE THREAD

**Issue by 71337** [oxen-io/session-ios#445]
### Bug description
When the client connect to a nodes the user's OS accepted language and system architecture are sended to nodes, any information regarding client when connecting should never be sended/leaked to anyone as it can in some ways cause privacy problems.
#### Expected result:
The accepted language and user's OS info should never be sended to onion nodes, this info should never be leaked in any way.

### Screenshots
![1997](https://user-images.githubusercontent.com/87157010/125007584-d3cf6a00-e060-11eb-9253-627da935f290.jpeg)

**iOS version**: Any Iphone

**Android version**: Any Android

**Session version:** Any version

**Comment by nielsandriesse** [comment]
Thanks for pointing this out! We now supply fake values for these headers both on iOS (https://github.com/oxen-io/session-ios/commit/5202bde4a462049d5ac424cdc8312e26d4d215c1) and Android (https://github.com/oxen-io/session-android/commit/7a388deb788919b0249fe6c7a7133e0cb3df60b1 and https://github.com/oxen-io/session-android/commit/bb1eb2310c449c10df148012fcccc3daefdb4337)

**Comment by nielsandriesse** [comment]
This'll all be included in upcoming releases; closing this issue :)
