### ISSUE TITLE
Reshowing read messages as unread

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#446]
Some open groups show unread messages permanently and jumps to those “unread” messages automatically even though you’ve already read them.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by nielsandriesse** [comment]
Hi @Sepero, can you check if this still happens for you on 1.11.11?

**Comment by Sepero** [comment]
Still occuring

**Comment by nielsandriesse** [comment]
Alright, we fixed a bug that could cause this, but it seems like it's a two part bug then :)

**Comment by RyanRory** [comment]
Hi @Sepero, I think this issue has been fixed in our latest build (version 1.11.21 build 319). Could you check if this issue still happens to you? If not, we'll close this issue happily. :) Thanks in advance!

**Comment by Sepero** [comment]
I've lost contact with the person I was reporting on behalf of, so unless someone new wishes to reopen it, we can consider this closed for now :)
