### ISSUE TITLE
Draft Edit Bug

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#447]
When editing a message on iOS after you’ve already closed the app, it’s not easily editable if the message is longer than the displayed characters. To get around this you need to use the space bar to move the cursor to where you can’t see it and start typing to reinitiate focus below the displayed text above. Otherwise scrolling doesnt work.

To Reproduce, write a long message without sending. Then, long press a message thats been sent and deselect it. Now you won’t be able to edit the rest of your message unless you do the work around stated above.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by RyanRory** [comment]
Hi @Sepero , happy to report that this issue has been fixed in our latest version. Thanks for the feedback. I'll close this issue :)
