### ISSUE TITLE
Editing new message scrolls/jumps to top

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#448]
Sometimes the text field scrolls to the top of the message when hitting a word.

To reproduce, write a long message and click on a mistyped word. It jumps to the top of the text message.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by GodGoldfish** [comment]
i tried to replicate this on iOS 15.2.1 & session 1.12.1 it seems this no longer happens.

**Comment by RyanRory** [comment]
Hi @Sepero @GodGoldfish , this issue seems to be resolved in one of our previous releases. I'll closed this for now. Cheers! :)
