### ISSUE TITLE
Draft Text Persists After Deletion

### ISSUE THREAD

**Issue by altosaxplayer** [oxen-io/session-ios#452]
**Code of conduct**

- [ ] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Deleting draft text using “Select All”, swiping back to see all messages, then returning to the draft message returns the draft text. 

Deleting from the end, character by character, successfully removes the draft. 

**Smartphone (please complete the following information):**

 - Device: iPhone 11 Pro Max
 - OS: iOS 14.6
 - Version of Session: Latest

**Additional context**

**Comment by RyanRory** [comment]
Hi @altosaxplayer, thank you for reporting this issue. It should be fixed in our new release (1.11.15). :)
