### ISSUE TITLE
Notifications even after muted

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#454]
Even though notifications are muted, sometimes notifications still come through. Not for every message. 

(Using slow mode)

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by Sepero** [comment]
This may be user error. Investigating further

**Comment by nielsandriesse** [comment]
This is an ongoing issue. We're working on fixing it :) .

**Comment by nielsandriesse** [comment]
This is now fixed and will be shipped with the next release!
