### ISSUE TITLE
Strange delays in receiving messages

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#458]
Sometimes receiving messages has a huge delay, although it has gotten better. For example, if you’re viewing messages in a group, all of a sudden an influx of messages may come in, well after they’ve been sent. You need to close session and reopen it to make sure its pulling messages every time.

These delays happen whether Session has been in foreground for several minutes or not. I'm having to constantly open and close session to poll for new msgs.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by RyanRory** [comment]
We've got multiple reports of delays in receiving messages, and we are working hard on fixing it. I'll close this issue for now. And we can move the discussion to #566. Cheers!
