### ISSUE TITLE
Sending messages to Open Groups when server is down

### ISSUE THREAD

**Issue by Sepero** [oxen-io/session-ios#459]
When an open group is no longer working and the server is down, you can still send messages to the group. The messages are marked as delivered even though the server is down. Should show as undelivered.

iPhone 12 Pro
iOS 14.6
Session 1.11.6

**Comment by nielsandriesse** [comment]
Good find @Sepero. There was a bug that was marking messages as delivered in open groups even when they actually failed. This'll be fixed as of the next round of releases.
