### ISSUE TITLE
App crash with false QR code when linking an account

### ISSUE THREAD

**Issue by Snocember** [oxen-io/session-ios#463]
**Description**

The application crashes when I scan a false QR code (not the restoration QR code) in the 'linking to existing account' dialog.

**Reproducing steps**

1. Open the app after the install
2. Go to "Link to an existing account"
3. Tap on "Scan QR code"
4. Scan a random QR code.
5. Crash.

**Smartphone:**

 - Device: iPhone 6s+
 - OS: iOS 14.6
 - Version of Session: 1.11.8 (262)

**Comment by RyanRory** [comment]
Hi @Snocember, this issue should be fixed in our new release (1.11.15). Thank you for reporting this. :)
