### ISSUE TITLE
I get notifications for messages when I am already looking at the conversation

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-ios#464]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When I do not have a conversation muted, I have the conversation open, when a friend sends a message in that conversation, I get an iOS notification for that message, even though I am already staring at the conversation.

**Smartphone (please complete the following information):**

 - Device: iPhone 8
 - OS: iOS 13
 - Version of Session: 1.11.8 (262)

**Additional context**

I am using Fast Mode notifications.

There is a Notification Setting toggle called "Play while app is open". I turned that off, hoping that it would fix this, but it did not.

I think that you just need to check to see if the notification is for the current conversation that the user is looking at. Should be a boolean check for what the user's current view is?

**Comment by lennylen** [comment]
+1 on iOS, can't replicated on Android

**Comment by RyanRory** [comment]
Hi @trosel @lennylen , could you check if this is still happening in the latest release?

**Comment by trosel** [comment]
Not exactly the same. I get notifications for my own messages when I exit the app before it fully sends. Then when it fully sends, I get notified for it.

https://github.com/oxen-io/session-ios/issues/470#issuecomment-903273106

**Comment by RyanRory** [comment]
@trosel  @lennylen  This should be fixed in version 1.11.16. Could you check if this still happens? Thanks in advance.

**Comment by RyanRory** [comment]
Thanks @trosel ! We finally located the issue. This will be fixed in next release. :)

**Comment by RyanRory** [comment]
Hi @trosel , happy to report this is fixed in 1.11.18 :)
