### ISSUE TITLE
Link Previews are unclear

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-ios#465]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

In the Privacy settings, there is the Link Previews option. The text underneath this setting says that it is only supported for 5 websites. But I think that this is no longer the case?

Did you pull in the Signal update that started generating link previews from the _sender's_ device instead of generating them from every _receiver's_ device?

Just want clarification on how this currently works and what the limitations are.

**Comment by nielsandriesse** [comment]
Hi @trosel, nice find. You're right that we now try to generate link previews for any website; not just those 5. We should adjust the text to reflect that.

**Comment by RyanRory** [comment]
Hi @trosel, this is fixed in version 1.11.16. :)
