### ISSUE TITLE
Image and video - UI Suggestions

### ISSUE THREAD

**Issue by lennylen** [oxen-io/session-ios#467]
Hi, Thank you for all of your hard work on session.

I have some suggestions regarding session-iOS, I hope they help:

I noticed that when sending a photo or video the preview is either blown up, and cropped, most of the time it doesn't look right. Could we have it thumbnail'd for a better experience?

In addition to that, the message accompanying the image could be displayed a lot better. Such as a separate bubble right below the image instead of overlaying the text on-top. 

IPhone 12 
iOS 14.6
Session 1.11.9

**Comment by trosel** [comment]
+1 here. Memes are just lacking oompf when the preview gets cropped and only part of the image is seen and they need to tap on it to see the rest.

**Comment by RyanRory** [comment]
We've separate the text and image for better display in version 1.11.18. Will keep improve the image presentation in the following releases. :)

**Comment by RyanRory** [comment]
Hi @lennylen @trosel , happy to report that the images shouldn't be cropped in our latest release anymore. :) I'll close this issue for now.
