### ISSUE TITLE
"Mentions and Replies Only" notification setting

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-ios#469]
**Code of conduct**

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When I "mute" a group chat, I expect to still get notifications for @ mentions and replies to my messages. In fact, the "mute" also mutes those messages too.

**To reproduce**

Select "mute" in a private group's settings.

**Smartphone (please complete the following information):**

 - Device: iPhone 8
 - OS: iOS 13
 - Version of Session or latest commit hash: 1.11.9 (265)

**Comment by nielsandriesse** [comment]
Hi @trosel, this is on our near-term to do list :) .

**Comment by nielsandriesse** [comment]
This is now implemented and will be shipped with the next release.

**Comment by trosel** [comment]
![4D46757F-55AF-43B7-BA77-D16B9EF39C08](https://user-images.githubusercontent.com/1299322/128641047-19c478dd-4a65-4cb3-91e8-30e5f6ded3ac.jpeg)

when i went to enable this, i already had “mute” enabled. so, what happens when mute and “mentions only” are both enabled? 

i love the quick turn around on this feature, but it seems like these two settings are mutually exclusive and should be part of the same notification “setting” / option @nielsandriesse

**Comment by nielsandriesse** [comment]
Agreed. It was just a bit more work to merge them together than we wanted to put into this right now. In the future we'll redesign this slightly so it makes more sense!
