### ISSUE TITLE
Getting notifications for my own messages

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-ios#470]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

In a private group, I’m getting notifications for my own messages. 

**To reproduce**

I had the private group on “mute” for a few days. When I unmuted, i started getting notifications for messages that I myself send to the group. 

**Smartphone (please complete the following information):**

 - Device: iPhone 8
 - OS: iOS 13
 - Version of Session or latest commit hash: 1.11.9 (265)

**Comment by nielsandriesse** [comment]
Hi @trosel, this is a known issue. It's on the to do list to fix it :) .

**Comment by nielsandriesse** [comment]
Happy to report that this is fixed. It'll be shipped with the next release.

**Comment by trosel** [comment]
This bug came back with most recent release btw

**Comment by trosel** [comment]
To recreate this bug, send a message in a close group and go to your homescreen as fast as possible. 

You will be notified of your own message when it finally sends to the convo because you are not in the app. 

If you leave the convo open, you of course won’t get any notifications and won’t notice this bug.
