### ISSUE TITLE
Swipe to reply doesn't work with short messages

### ISSUE THREAD

**Issue by malmazuke** [oxen-io/session-ios#482]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When attempting to reply to a message, if the message is too short the user is unable to reply to the message. This is caused by the swipe/translation distance being unable to exceed the `swipeToReplyThreshold` due to proximity to edge of screen:
https://github.com/oxen-io/session-ios/blob/master/Session/Conversations/Message%20Cells/VisibleMessageCell.swift#L483-L489

This only applies to received messages, as they are on the left-hand side of the screen (and swipe-to-reply is left-swipe)

**To reproduce**

- Receive a message that is fairly short
- Attempt to swipe to reply to the message

**Screenshots or logs**

![swipeToReply](https://media.giphy.com/media/rZJerjPMHHzsqsk6pL/giphy.gif)

**Smartphone (please complete the following information):**

 - Device: iPhone 12 Pro Simulator
 - OS: iOS 14.5
 - Latest commit hash: 5bd5400

**Additional context**

Could potentially fix the issue by setting the `swipeToReplyThreshold` to either [the default (130)](https://github.com/oxen-io/session-ios/blob/master/Session/Conversations/Message%20Cells/VisibleMessageCell.swift#L124), or the width of the message view - whichever is smaller.

**Comment by Prophet-26** [comment]
You have to swipe from further to the right. Pretend as if the text bar spreads across the whole screen. It's not very intuitive but it works.

**Comment by malmazuke** [comment]
Ah gotcha. I’ll close this issue
