### ISSUE TITLE
Messages from Desktop, don't appear on iOS

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#487]
**Describe the bug**

In closed groups, many of the messages written on latest Session Desktop (MacOS 11.5.1, Session 1.6.10) will not appear on Session iOS.

**Screenshots or logs**

Screenshots taken at the same time. Latest version of closed group.

Session iOS
![20210811_085343000_iOS](https://user-images.githubusercontent.com/77722427/129000981-b189a8c5-2d25-43a3-8811-881c6ff38e53.jpg)

Session Desktop
<img width="696" alt="Screenshot 2021-08-11 at 11 53 40" src="https://user-images.githubusercontent.com/77722427/129001057-7715bc6d-d506-485a-8199-05345e9e435c.png">

**Smartphone (please complete the following information):**

 - Device: iPhone 11
 - OS: iOS 14.7.1
 - Version of Session 1.11.13

**Comment by Marky-N** [comment]
This issue doesn't seem to be affected on V1 Closed groups.

**Comment by Marky-N** [comment]
This issue doesn't either appear on 1-1 discussion or in open groups. So seems only to be an issue with Closed Groups v2.

**Comment by RyanRory** [comment]
Hi @Marky-N , can you check if this still happens for you on version 1.11.15?

**Comment by Marky-N** [comment]
@RyanRory I'm monitoring this and will get back to you when I see I it still appears or not

**Comment by RyanRory** [comment]
Thanks @Marky-N Could you check if this still happens on version 1.11.16? Cheers!

**Comment by Marky-N** [comment]
@RyanRory With the test I did, it seems to be working now!
Will get back to this issue if the issue appears again. Thanks!

**Comment by RyanRory** [comment]
@Marky-N Thanks, happy to see this is finally fixed. I'll close this issue now. :)
