### ISSUE TITLE
Copying link not possible (Feature request)

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#488]
**Describe the feature**

Within Session, it's impossible to copy a link. You get the options "Cancel" or "Open". It would be good to have a third option "Copy".
This is a issue if someone pastes a link to an open group, as this means that you have to open the link in a browser (which of course doesn't work, copy the link from the browser and go back to Session, go out from the chat where the link was, "+" and choose "Open group".

**Screenshots or logs**

![20210811_091540000_iOS](https://user-images.githubusercontent.com/77722427/129003388-47744b05-5386-44f4-bd37-642ff2c7c869.png)

**Comment by Marky-N** [comment]
This is kind of duplicate with this issue:
https://github.com/oxen-io/session-desktop/issues/1842

**Comment by RyanRory** [comment]
Hi @Marky-N , this is on our near-term to do list :) .

**Comment by Marky-N** [comment]
@RyanRory Yes, saw the feature on the Desktop-version already.

**Comment by RyanRory** [comment]
Happy to say we now have the copying link option in the new release (version 1.11.15) :)
