### ISSUE TITLE
No @ symbol  showing that you were quoted

### ISSUE THREAD

**Issue by lennylen** [oxen-io/session-ios#490]
If you were @'d or quoted, you won't know until you manually scroll past message history. On desktop this feature works as expected but not on iOS

Thank you

**Comment by RyanRory** [comment]
Hi @lennylen , this is on our to do list now.

**Comment by RyanRory** [comment]
Happy to report that we have this feature now on Session iOS version 1.11.15

**Comment by lennylen** [comment]
Thanks for adding the feature. However, when I am quoted, there is no @ symbol to click on to take me to where I was quoted. I do see an @ symbol in the chat preview line but there is no @ symbol jump button. Is this the desired functionality?

Thank you
