### ISSUE TITLE
Appearance setting to switch between light / dark mode based on system settings [feature request]

### ISSUE THREAD

**Issue by trosel** [oxen-io/session-ios#491]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the feature**

As a user, I want an appearance setting that switches between light and dark mode based on my system settings so that I can have light mode during the day and dark mode at night.

**Comment by glottis0q** [comment]
this is done

**Comment by RyanRory** [comment]
Hi @trosel, happy to report this feature is added in 1.11.18. :)

**Comment by trosel** [comment]
beautiful!
