### ISSUE TITLE
App Crashes when trying to send photo from gallery or Take a photo on iOS

### ISSUE THREAD

**Issue by xardinero** [oxen-io/session-ios#498]
### Bug description
App crashes for my friend when trying to send me a photo from gallery or camera on his iphone 12 mini.

### Steps to reproduce
- Try to send photo on iPhone 12 mini or share from gallery

#### Actual result:
The app crashes and no photo is sent

#### Expected result:
-The app wouldn't crash, and the photo would be received

### Device info
**Device**: iPhone 12 mini

**iOS version**: 14.7.1

**Session version: 1.11.14(291)

**Comment by RyanRory** [comment]
This should be fixed in the new release(version 1.11.15) :)
