### ISSUE TITLE
[BUG] Freeze typing message

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-ios#505]
The application slows down when typing message

1) if new messages are received in the chat
2) if there are a lot of images in the chat
3) if the chat shows the status of typing by the interlocutor

I believe that all these actions should not slow down the interface and text input should go separately (thread)

**Comment by GodGoldfish** [comment]
I think that this issue is related to device's performance, i tried this on an iPhone 13 Pro iOS 15.2.1 Session 1.12.1 and had no slow down. this issue needs more investigation.

**Comment by xbvrhlmb** [comment]
Most likely it has already been fixed, since this bug was on the android version and then it was fixed

**Comment by RyanRory** [comment]
Hi @xbvrhlmb @GodGoldfish, seems like this issue is not happening anymore. I'll closed it for now. Thanks for the reports and updates.
