### ISSUE TITLE
Don't Show Mention (@) Indicator on Conversation Cell for One-on-One Chats

### ISSUE THREAD

**Issue by nielsandriesse** [oxen-io/session-ios#508]
In a one-on-one chat, if someone replies to a message you sent, the mention (@) indicator will show up for that conversation on the home screen. Seems more sensible to only do that in group chats. In a one-on-one chat if there's an unread message it's already clear that the other party is addressing you.

**Comment by RyanRory** [comment]
Yeah, that makes perfect sense. Will fix this in the next release.

**Comment by RyanRory** [comment]
This is fixed in version 1.11.16 :)
