### ISSUE TITLE
Display or Support the HD Profile Image

### ISSUE THREAD

**Issue by Pingmin** [oxen-io/session-ios#511]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the Bug**

Comparing to the Session Desktop, the user's profile image on Session iOS doesn't display in HD.

**To Reproduce**

On Session iOS App:

- Upload and set a HD profile image in top-left profile settings.

- Go to "Note to Self" and click the avatar on the top-right icon.

- Click the profile image of yourself to see the large size profile image.

- You'll see a blurred/dim profile image, while the Session Desktop will display a HD profile image.

**Screenshots or Logs**

None.

**Smartphone**

 - Device: iPhone SE
 - OS: iOS 15.0
 - Version: Session iOS v1.11.16

**Additional context**

None.

**Comment by RyanRory** [comment]
Hi @Pingmin , the definition on iOS is higher in the new release. This issue should be fixed. :)

**Comment by Pingmin** [comment]
> Hi @Pingmin , the definition of avatars on iOS is higher in the new release. This issue should be fixed. :)

Thank you! Good job!
