### ISSUE TITLE
session on iphone6s crash when ...

### ISSUE THREAD

**Issue by apitest000** [oxen-io/session-ios#512]
i have no username because i use old version long long ago , but when i update the version on APPSTORE, and changing the username from null to other string, it causes app crash 100% on iphone6s... please check this, and try to fix it, thx!

To reproduce

Try to set a nickname for myself, from not having nickname to other random name.

IOS 14.3
Iphone 6s

**Comment by RyanRory** [comment]
This seems to be fixed already, I'll just closed this issue.
