### ISSUE TITLE
IOS Webcam indicator is being shown when not using webcam. 

### ISSUE THREAD

**Issue by The-Real-Thisas** [oxen-io/session-ios#514]
**Code of conduct**

- [*] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Description**

When installed in a new device running the latest version of ios, a green indicator appears in the top right showing the use of the camara. 

**To reproduce**

Install the latest version of ios (15.0.1), try to send images and give access to the camera. A green indicator should appear even after out of the menu which shows active use of the camara. This should not happen. 

**Smartphone (please complete the following information):**

 - Device: Iphone X 
 - OS: IOS 15.0.1
 - Version of Session or latest commit hash

**Comment by GodGoldfish** [comment]
> **Code of conduct**
> 
> * [*] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).
> 
> **Description**
> 
> When installed in a new device running the latest version of ios, a green indicator appears in the top right showing the use of the camara.
> 
> **To reproduce**
> 
> Install the latest version of ios (15.0.1), try to send images and give access to the camera. A green indicator should appear even after out of the menu which shows active use of the camara. This should not happen.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Iphone X
> * OS: IOS 15.0.1
> * Version of Session or latest commit hash

This issue can be closed, as i know this no longer happens anymore on the last version of iOS 15.2.1 and/or session 1.11.20/1.12.1

**Comment by RyanRory** [comment]
Hi @The-Real-Thisas @GodGoldfish. Thanks for the report. Seems like this issue has been fixed / not happening anymore. I'll just close this issue for now. Cheers!
