### ISSUE TITLE
Disappearing message doesn't work for new sessions

### ISSUE THREAD

**Issue by ff7f00ff** [oxen-io/session-ios#515]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

The "disappearing message" feature doesn't work for a new session.

**To reproduce**

I have 2 phones: one Android (Phone A), one iPhone (Phone B)

1. Use a newly created account on Phone A to start a new session with the Session account on Phone B (by scanning the QR Code of the account ID on Phone B). Do not send any messages. 
2. Set "Disappearing messages" to like 30 seconds. So far there's nothing happened on Phone B.
3. Send out a few messages in that session.
4. Phone B receives the messages without any timers set - they just persists, unless you set a timer (not necessarily need to be the same time as on Phone A) on the Phone B side.

**Smartphone (please complete the following information):**

 - OS: iOS 15.0
 - Version of Session: 1.11.17

**Additional context**

It seems the macOS version (version 1.7.3) which acts as Phone B works without this issue.

**Comment by robster7674** [comment]
I've seen similar behavior on iOS when the disappearing timer was inadvertently set from one week back to Off. It seems that messages created during the time the timer was Off will not disappear even after setting the timer back to for example one week, they remain. In hostile environments this could be dangerous when someone's phone is confiscated by authorities. Please ensure that messages always disappear when set by the user to do so.

**Comment by RyanRory** [comment]
Hi @robster7674, could you open another Github issue? The issue @ff7f00ff reported is fixed in fixed in 1.11.18. :)
