### ISSUE TITLE
Receiving new message

### ISSUE THREAD

**Issue by lennylen** [oxen-io/session-ios#518]
There have been amazing improvements in the last update when it comes to receiving or sending messages, namely in open groups. 

However, I find the occasional message gets missed and you still need to restart the app to receive them. Meaning if you sent messages before closing the app, you would see new messages on top of your latest messages.

Session 1.11.17
iOS 14.7

**Comment by RyanRory** [comment]
We've got multiple reports of delays in receiving messages, and we are working hard on fixing it. I'll close this issue for now. And we can move the discussion to #566. Cheers!
