### ISSUE TITLE
Service Nodes are stuck on US

### ISSUE THREAD

**Issue by 144** [oxen-io/session-ios#522]
**Describe the bug**

That's my second time my service nodes patch is stuck at only US nodes (including Entry), last time it lasted 1 month before they changed. I assume they should change every time you restart the app, like they do on Desktop and usually on mobile in my case.

**To reproduce**

Can't really trigger it in any way, it happens randomly.

**Smartphone (please complete the following information):**

 - Device: iPhone 12
 - OS: iOS 15.0.2
 - Version of Session: 1.11.17

**Comment by RyanRory** [comment]
Hi @144 , as we understand, the service nodes selection for path building is a totally random process. It is rare to see all the nodes are only from US. And on iOS, the path should be rebuilt every time the app restarts. We'll look into it and see if there is any corner case that may cause this issue.

**Comment by RyanRory** [comment]
Hi @144 , we couldn't find anything on the client side and we think this is a random case, it shouldn't happen all the time. Just want to check with you if this issue continues happening on your phone? Thanks in advance.

**Comment by 144** [comment]
> Hi @144 , we couldn't find anything on the client side and we think this is a random case, it shouldn't happen all the time. Just want to check with you if this issue continues happening on your phone? Thanks in advance.

Hey, sorry for late reply. It in fact seems to be fixed, I think there might be a bug with server selection keeping servers from previous "session". I do not think "US" are exclusive are something, but yeah.  It might be related to server selection algorithm.

Regards,

**Comment by RyanRory** [comment]
That's good, thanks for the reply @144 , I'll close this issue for now.
