### ISSUE TITLE
Degraded search performance

### ISSUE THREAD

**Issue by lennylen** [oxen-io/session-ios#523]
When writing a keyword to search, session freezes and runs really slow. It can eventually search the key word but not without lockups.

Reproduce: go into any open group, click search, start typing. Session will start locking up and in some cases exit prematurely. Phone gets really hot during this process if you let it complete the processes involved.

**Comment by GodGoldfish** [comment]
> When writing a keyword to search, session freezes and runs really slow. It can eventually search the key word but not without lockups.
> 
> Reproduce: go into any open group, click search, start typing. Session will start locking up and in some cases exit prematurely. Phone gets really hot during this process if you let it complete the processes involved.

I think that this issue is related to device's performance, ti tried this on an iPhone 13 Pro iOS 15.2.1 Session 1.12.1 i had no problem, no freeze, no crash in fact it was revelant and fast. this issue needs more investigation.

**Comment by RyanRory** [comment]
Hi @lennylen @GodGoldfish, thanks for the report. It is true the performance is related to how powerful the device is. And we are looking into improving the performance of Session as well. :)

**Comment by RyanRory** [comment]
Hi @lennylen @GodGoldfish , we did a lot of performance improvements in 1.11.22. I believe the performance for searching is much better now. We'll continue to improvement Session's performance and user experience. :grinning: I'll close this issue for now.
