### ISSUE TITLE
Sharing to Session gives only icon, not the actual shared item

### ISSUE THREAD

**Issue by robster7674** [oxen-io/session-ios#528]
- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

When sharing an item, for example an URL from a browser, to Session, this results not in the actual item, but just an icon.  Example:
![image](https://user-images.githubusercontent.com/70331923/141424315-9137a82f-0788-4b69-86a0-865777f2e7f6.png)

### Steps to reproduce
- visit a web page
- from browser, tap Share
- select Session and a conversation
- tap Share

#### Actual result:
Describe here what happens after you run the steps above (i.e. the buggy behaviour).
An icon shows up in the selected conversation.

#### Expected result:
Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour).
The item (URL, picture, file) should be shared with the conversation in Session.

### Device info

**Device**: iPhone XS

**iOS version**: 15.0

**Session version:** 1.11.18 (306)

**Comment by RyanRory** [comment]
@robster7674 Thanks for the reporting, this is a know issue on our to do list. Will fix this in the future release. :)

**Comment by robster7674** [comment]
Excellent, thanks @RyanRory - great to see this is at least known already. ;)

**Comment by RyanRory** [comment]
Hi @robster7674, happy to report that the whole process of sharing to Session has been improved in the latest release! :)
