### ISSUE TITLE
App doesn't scroll to last message received even though all messages read or no new message shown

### ISSUE THREAD

**Issue by dsincl12** [oxen-io/session-ios#543]
**Describe the bug**

When a message has been received in a group, the read position is wrong so you need to scroll to the bottom yourself. Sometimes the message isn't shown at all so you have to force quit the app and start it again to receive it.

**To reproduce**

Read all messages in a group, go to home screen and use another app, receive message, open app again, scroll position isn't where the new message is so you have to scroll to the bottom yourself to see it and sometimes no new message is shown at all.

**Smartphone (please complete the following information):**

 - Device: iPhone 13
 - OS: iOS 15.1.1
 - Version of Session: 1.11.20 (316)

**Comment by dsincl12** [comment]
This seems to be an overall issue as well. Open the app, go into a group or conversation, the scroll position isn't at the bottom so you need to scroll down so see the last messages even though all messages are read.

**Comment by RyanRory** [comment]
Hi @dsincl12 , thanks for reporting the issue. This is an known issue and we are working on it. Hopefully this can be fixed in next release. :)

**Comment by GodGoldfish** [comment]
> Hi @dsincl12 , thanks for reporting the issue. This is an known issue and we are working on it. Hopefully this can be fixed in next release. :)

this seems only to happen when someone delete a message for everyone on the version 1.12.1

**Comment by RyanRory** [comment]
@GodGoldfish Thanks for the feedback! We did fix something in 1.12.1 and we'll keep working on this. Cheers!

**Comment by DillFrescott** [comment]
It happens to me all the time, not just when somebody deletes a message...

**Comment by RyanRory** [comment]
Hi @dsincl12 @GodGoldfish , happy to report this issue should be fixed in our latest release (1.11.21)!
