### ISSUE TITLE
[BUG] Send Image or Video

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-ios#544]
**Describe the bug**

if user open chat and click send (Plus) after click Gallery (Image) after i see white background and top text "Recent"
if click in top "Recent" not see other gallery dir

That is, the user cannot select photos from the gallery (he does not see them)

you can only see a white background without a photo and there is no way to select a folder with a photo.

**To reproduce**
join to chat
click send image

**Smartphone (please complete the following information):**

 - Device: iPhone 11
 - OS: 14.7.1
 - Version of Session latest

**Comment by RyanRory** [comment]
Hi @xbvrhlmb , it seems like a permission issue. Could you make sure you give access to photos for Session in the system settings? Cheers!

**Comment by xbvrhlmb** [comment]
> Hi @xbvrhlmb , it seems like a permission issue. Could you make sure you give access to photos for Session in the system settings? Cheers!

Hi @RyanRory
Yes, you're right, the problem was that access was granted not to "All photos" but only to "Selected photos"
I'm not an iPhone user so I didn't know)

P.S I think it would be great to remind the user to enable access (to all photos) when he sends a photo but does not see the image. 
This way the interface will be more user-friendly and will give him tips on what to do.

**Comment by RyanRory** [comment]
Hi @xbvrhlmb , good to hear there is no issue there. In fact, we can't really know if users can see the images or not. But we'll see what we can do to improve the experience. :) I'll close this issue for now.
