### ISSUE TITLE
[UI] Font color in day thema

### ISSUE THREAD

**Issue by xbvrhlmb** [oxen-io/session-ios#545]
if use day theme in chat and see self message
we have green background and white text

maybe better green background and black font color?

**Comment by RyanRory** [comment]
Hi @xbvrhlmb , that's a good suggestion. I'll talk to our designer to make it clearer in day theme. Cheers!

**Comment by RyanRory** [comment]
Hi @xbvrhlmb, happy to report we have improved the text colour in day theme to Session Grey in our latest release (1.11.21)!
