### ISSUE TITLE
[Translate] Media saved 

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-ios#546]
Now in chat if user save image, see text "Media saved by Username" but not have translate in other lang
(Desktop version have)

i not see this in crowdin

**Comment by RyanRory** [comment]
Hi @xbvrhlmb , I'll check and add that to Crowdin. Cheers!

**Comment by xbvrhlmb** [comment]
@RyanRory, please add Russian translate

screenshot_taken = %@ сделал(а) снимок экрана.
meida_saved = %@ сохранил(а) медиафайл.

Thanks. Cheers!)

**Comment by RyanRory** [comment]
Happy to report the translation is updated. I'll close this issue. Thanks for the feedback.
