### ISSUE TITLE
(UI GLITCH) Messages are notified but not displayed in the conversation 1:1 [1.12.1]

### ISSUE THREAD

**Issue by GodGoldfish** [oxen-io/session-ios#551]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

As the title says, the messages are notified but not displayed in the feed of the conversation in a 1:1 exchange (didn't try in a group chat).

**To reproduce**

One of the person has to leave the conversation by going on an other application (doesn't really matter just need to leave) but needs to stay in the conversation feed of the 1:1 conversation before leaving, the other person needs to text this person that is away of the application (but for the app still inside the feed), the person that was away has to get back when he sees the notifications (by clicking on the notifications or by going on the application again it doesn't really matter) and once back the messages will not be displayed and the person will need to go on the home screen of session and then go back in the conversation to finally see the messages. 

**Screenshots or logs**

Haven't been able to take screenshots

**Smartphone (please complete the following information):**

 - Device: Tested on iPhone 13 & 11
 - iOS: 15.2 & 15.2.1
 - Version of Session : 1.12.1 (i don't remember this happening on previous version but i didn't try so someone could try to be sure.)

**Additional context**

A hot fix is to leave the application in the session's conversation menu so when the messages are notified they are displayed normally (by clicking on the notifications or by going on the application).

**Comment by GodGoldfish** [comment]
seems to look like this issue : https://github.com/oxen-io/session-ios/issues/518

**Comment by brettohland** [comment]
I'm seeing this issue a lot too. 

As a curiosity, I took a quick pass through the source code and it looks like the main issue is that the app isn't fully reloading it's data stores when the app returns to an active state. Because the notifications are dependent on the push certificates assigned to the Loki development account, it's difficult to give this a proper test.

**Comment by RyanRory** [comment]
We've got multiple reports of delays in receiving messages, and we are working hard on fixing it. I'll close this issue for now. And we can move the discussion to #566. Cheers!
