### ISSUE TITLE
Open groups joined on desktop not showing up on iOS.

### ISSUE THREAD

**Issue by DillFrescott** [oxen-io/session-ios#554]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

Open groups joined on desktop not showing up on iOS.

**To reproduce**

Join a group on windows Session desktop client. It won't show up on iOS app.

**Screenshots or logs**

n/a

**Smartphone (please complete the following information):**

 - Device: iPhone XS
 - OS: iOS 15.2.1
 - Version of Session or latest commit hash: 1.11.20

**Additional context**

n/a

**Comment by GodGoldfish** [comment]
Yes i can confirm this issue on the last version of Session Desktop 1.7.6 & Session iOS 1.12.1

**Comment by RyanRory** [comment]
Hi, @DillFrescott @GodGoldfish , happy to report this issue should be fixed in 1.11.22. :grinning:
