### ISSUE TITLE
Message with two links, second link uses address of first

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/session-ios#587]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
This happens at least in a closed group.

Message on iOS with two links, if pressing first link it uses it correctly and it can either be copied or opened.
![20220316_194809000_iOS](https://user-images.githubusercontent.com/77722427/158679170-daeb125b-3f67-4bd4-8726-c6616c83a243.png)

Second link works, but when pressing it, the address of the first link is used instead of the address for the second link.
![20220316_194823000_iOS](https://user-images.githubusercontent.com/77722427/158679193-7bb7f26b-7127-4ae0-903c-760c9e9e8921.png)

**To reproduce**

Believe this is quite clear

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [iPhone 12 mini]
 - OS: [iOS 15.3.1]
 - Version of Session 1.11.21

**Additional context**

**Comment by RyanRory** [comment]
Hi @Marky-N , this issue has been fixed in our latest build 1.11.23, thanks for your report!
