### ISSUE TITLE
The app closes when you paste a url into group chat

### ISSUE THREAD

**Issue by adanmazzoli** [oxen-io/session-ios#606]
### Bug description

The app drops when you paste some urls into the group chat.

#### Actual result:

A url is copied from a web page and pasted into the chat, then the app is closed.

#### Expected result:

Copy a url from any web page and paste it into the chat and then send it to the group.

### Device info

**Device**: iPhone X,XS,XS Max,XR

**iOS version**: 15.4

**Session version:** 1.11.23

**Comment by RyanRory** [comment]
Hi @adanmazzoli, thanks for the report. This is a known issue and we'll fix it in the next release. Cheers! 🙂

**Comment by Marky-N** [comment]
> Hi @adanmazzoli, thanks for the report. This is a known issue and we'll fix it in the next release. Cheers! 🙂

@RyanRory This also happens when pasting any text including a link into any chat (open/closed/dm) with 1.12.5 version from TestFlight.

**Comment by RyanRory** [comment]
Hey @Marky-N, thanks for the feedback. Yes, this is a crash regarding all links if you enabled the link preview. We are about to release a new version including the fix of this issue. Cheers!

**Comment by RyanRory** [comment]
This issue should be fix in the latest release 1.11.24 and 1.12.6. :)
