### ISSUE TITLE
Ultra slow reaction on displaying keyboard when tap the message box

### ISSUE THREAD

**Issue by http403** [oxen-io/session-ios#618]
**Code of conduct**
- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
The message box in one-to-one, closed group chat in-app are slow to show the keyboard when tapped. I need multiple taps to get the keyboard to show. Other text box like search and in share extension responed in acceptable timeframe. 

**To reproduce**
Unknown. After installation, I have two contacts added then the bug appears. I have tested that the touch screen is working properly.

**Screenshots or logs**
Video: https://user-images.githubusercontent.com/8369976/165730489-dcfcf0d9-b559-4318-a0ff-82e496b79645.MOV

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS 12.5.5
 - Version of Session or latest commit hash: 1.12.7 (342)

**Comment by KeeJef** [comment]
is this still occurring? @http403

**Comment by http403** [comment]
I have no idea as I switched my phone. Shall I close this issue?
