### ISSUE TITLE
the video's resolution is turn to very low when senting file to someone

### ISSUE THREAD

**Issue by neiriiod** [oxen-io/session-ios#619]
issue: when i try to senting a video file to someone, and then the video's resolution is turn to very low.
         like my original video's resolution is atleast 720p, but it turn to 270p or 360p.

hoping: i hope the video's resolution can stay the same when senting video to someone.

os: iphone xs max
ios: 13.3.1
session verison: 1.12.6(334)

**Comment by KeeJef** [comment]
Closing for now, aggressive compression is a side effect of our current file size limitations, we are aiming to increase the maximum file size soon, but we need a few network changes in place before this can take effect
