### ISSUE TITLE
please add otption to resize user's view

### ISSUE THREAD

**Issue by neiriiod** [oxen-io/session-ios#621]
here is the srceenshot in my phone
![Snipaste_2022-05-01_14-14-24](https://user-images.githubusercontent.com/61473577/166134634-3e587eb9-3eb5-403d-81c1-cecfaaa2ea01.png)

when i try to having a video call with someone, but my view is too samll, almost can't see myself ,
and i can't find any option to resize my view, which make it to a big view.
so please add option to resize user's view.

os: iphone xs max
ios: 13.3.1
session verison: 1.12.6(334)

**Comment by KeeJef** [comment]
i think if we added #620 this would not be required
