### ISSUE TITLE
Swiping from left edge make the input field disappear 

### ISSUE THREAD

**Issue by mmahmoudian** [oxen-io/session-ios#628]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

When in a chat (one-to-one or in a group), when swiping from the left edge halfway and back, the input field and the keyboard disappear and there is no way to get them back unless we go back to the list of chats and get back in the chat.

**To reproduce**

1. open session
2. go to a chat (note that the input field is visible at the bottom of the screen)
3. swipe from left-side of the screen (in iOS this is typically used to go back) but only half way, then let it snap back its place
4. observe that the input field is gone and there is no way to get it back.

**Screenshots or logs**

https://user-images.githubusercontent.com/390889/169818445-65188d49-3c82-448e-85be-31c6e6bd0a97.MOV

**Smartphone (please complete the following information):**

 - Device: iPhone 12 mini
 - OS: iOS 15.5
 - Version of Session or latest commit hash: 1.12.8 (344)

**Additional context**

-None-

**Comment by RyanRory** [comment]
Hey @mmahmoudian, thanks for the feedback. This issue is fixed in our latest version 1.12.9. Cheers!
