### ISSUE TITLE
Chat history and contacts lost after device upgrade

### ISSUE THREAD

**Issue by sclsj** [oxen-io/session-ios#642]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

After migrating to a new device by making and restoring an encrypted iTunes/Finder backup, all other applications (after re-authentication) works just as before. Session, after entering the recovery phrase, seems to delete the chat history and contacts.

**To reproduce**

Migrate to a new iOS device.

**Screenshots or logs**

**Smartphone (please complete the following information):**

 - Device: Any
 - OS: Any
 - Version of Session: Any

**Additional context**

This is a big problem if you lost your iPhone, it is stolen/broken, or it is no longer supported by Apple and needs upgrade to newer device.

**Comment by RyanRory** [comment]
Hi @sclsj , thanks for the feedback! If you use recovery phrase to restore your account, you can only get the latest 14-day chat history from network. All the messages stored on the network have a TTL(time to live) of 14 days. 

Regarding the migration, Session should be able to be migrated by the proper iPhone backup including all the data of your previous Session app.
