### ISSUE TITLE
Authentication should be required to enable "Screen Lock".

### ISSUE THREAD

**Issue by 3m4r5** [oxen-io/session-ios#643]
**Code of conduct**
- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Bug distribution:**
you can enable Screen Lock without having FaceID / TouchID & Passcode set up, which results in locking the user out of the app with no way to authenticate.

**Steps to reproduce:**
1- Disable Passcode.
2- Enabled the "Screen Lock" feature from privacy options.
3- re-open the app.

**[Screen recording](https://user-images.githubusercontent.com/63432932/178112857-51fb531a-9a66-4c6a-8ccc-bf4b4c3aa1ff.MOV)**

**Smartphone:**
 - Device: iPhone 8 Plus
 - OS: 14.7.1
 - Version of Session: 1.13.0

**Comment by RyanRory** [comment]
Hi @3m4r5, happy to report this issue should be fixed in 2.2.6. I'll close this issue for now. Thanks for the feedback!
