### ISSUE TITLE
Couldn't find enough Service Nodes to build a path

### ISSUE THREAD

**Issue by robster7674** [oxen-io/session-ios#695]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
Recently, when sharing something from various apps to Session iOS, I'm getting a popup telling me "Couldn't find enough Service nodes to build a path."

This seems to have started after the recent update to Session 2.1.0 (374).

**To reproduce**

Steps to reproduce the behavior.
- open Firefox
- visit a page
- share link to Session chat
- result:
![image](https://user-images.githubusercontent.com/70331923/192780335-33c17e17-04e0-4b27-833f-ef53b64dca7a.png)

**Smartphone (please complete the following information):**

 - Device: iPhone XS
 - OS: iOS 15.2.1
 - Version of Session or latest commit hash: 2.1.0 (374)

**Comment by KeeJef** [comment]
Is this still occurring? typically this happens if you can get in contact with the seed nodes, which could happen if you are using Session on a firewalled network

**Comment by robster7674** [comment]
@KeeJef : just tested with version 2.2.3 (388) and the issue seems gone. Note that this seemed to happen with only some apps, not all. For now I'll close.

**Comment by Shawzborne** [comment]
This bug still exists in the latest version. Case re-opened. 

Hi Session team, 

I am unable to share links, files and images to users on iOS 16.3.1 using the iOS share sheet. 

Session app version 2.2.7 (392) Other users are having issues as well. 

Thank-you, 
Shawn

![image](https://user-images.githubusercontent.com/5931778/223463302-323e8b8f-db37-408f-95b6-7a2338acfd2d.jpeg)
