### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by BeHooman** [oxen-io/session-ios#698]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the request**

My request is to have Session app working in landscape mode, both on iPhone and iPad.

**Comment by RyanRory** [comment]
Landscape mode is available on iPad with our latest release (2.2.3), we'll continue to work on improving the landscape mode on iPad and supporting landscape mode on iPhone.
