### ISSUE TITLE
Latest update crashes closed group

### ISSUE THREAD

**Issue by lennylen** [oxen-io/session-ios#700]
The latest update now crashes session more than ever when participating in a closed group.

Not sure what is crashing it but some message or media or tag is crashing the app when scrolling up. 

iOS 15.6.1
Session 2.1.1

**Comment by mpretty-cyro** [comment]
We will be doing a release in the coming days which includes a number of crash fixes - there was an issue where messages which contain a mention followed by a link was crashing which could be the issue you are experiencing

Please let us know if you continue to experience issues with version 2.2.0

**Comment by KeeJef** [comment]
Closing for now, please reopen if you are still experiencing crashes in closed groups
