### ISSUE TITLE
Session user name disappear on the old device when link a new device

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-ios#723]
**Code of conduct**

- [x] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**

This might be a regression, not sure when it starts. Reproducible on both Session iOS 2.2.0 and Session iOS 2.2.1.

**To reproduce**

Old device: Session Desktop / Session iOS
New device: Session iOS

Steps:

1. create a fresh new Session ID on an old device with the user name "Test"
2. "Link a device" from the new device to the old device

Expect result:
Both old device and new device has the same user name "Test"

Actual result:
Old device has no user name anymore, not sure if it's an empty string or a NULL pointer.
New device has the correct user name "Test"
Edit: after syncing for a while, new device lost its user name as well.

It seems impossible to edit the user name on the old device anymore, the user name input box on the old device is non-editable after linking the new device.

<img width="154" alt="Session user name" src="https://user-images.githubusercontent.com/194342/197710464-ccec8daa-f68e-47f4-94da-0fc3b75250aa.png">

You can also tell from the Avatar placeholder, it's no longer an abbreviate of user name, it becomes completely empty.

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: iPhone SE, iPad
 - OS: iOS 15.6
 - Version of Session: 2.2.0 / 2.2.1

**Additional context**

We need better test cases to cover this kind of weird edge case :D

**Comment by KeeJef** [comment]
We are currently working through config message management (including profile managment) using libsession-util, hoping that this issue will get resolved as part of that effort

**Comment by fracting** [comment]
Thanks for the response, I'll retest this one once the new release is available.

**Comment by fracting** [comment]
I retested Session iOS 2.2.5, and can still reproduce it @RyanRory 

Fresh created new account
First device: Desktop v1.10.4
Second device: iOS 2.2.5

**Comment by fracting** [comment]
Update:

Works fine when both the first device and the second device are iOS. Maybe a desktop bug.

**Comment by fracting** [comment]
|                     | iOS (1st) | Desktop (1st)             |
|---------------------|---------------|-------------------------------|
| iOS (2nd)     | works         | primary device lost user name |
| Desktop (2nd) | works         | works                         |

More complex behavior happens when there are more than two devices sharing the same account, instead of losing the user name, I see a user name "Anonymous".

**Comment by fracting** [comment]
Probably better wait for https://github.com/oxen-io/libsession-util integration

**Comment by mpretty-cyro** [comment]
@fracting There are currently a few issues with how user information is syncing between devices, this is the next feature release that we are currently working on (#751) which implements a C library across all of the platforms to standardise how "conflict resolution" works across Session when two devices make changes at the same time as well splitting out the messages which sync device info so they can be handled sooner and independently from normal messages

In terms of what's currently happening, it's likely that the 2nd device to be linked is sending new, invalid user info before it's properly processed the user info from the first device

**Comment by fracting** [comment]
Thanks, I'm aware of the work on #751 , great job!

> the 2nd device to be linked is sending new, invalid user info before it's properly processed the user info from the first device

To me it seems the current situation could be improved without waiting for #751 though.

**Comment by fracting** [comment]
Are you interested if I debug the problem and suggest a potential fix (in the weekend), or do you have time to take a look by yourself this week, or do you prefer to fix related things all together when #751 is done?

I'm happy with either way though, nice to hear your comment!

**Comment by mpretty-cyro** [comment]
Closing this as #751 has been live for quite a while, feel free to open a new issue if you experience any problems syncing accounts between different devices
