### ISSUE TITLE
Disappearing messages reappear on multiple devices

### ISSUE THREAD

**Issue by smss2022** [oxen-io/session-ios#725]
**Note: this should probably go under lokinet or oxen-core, but a quick glance at their current issues made me hesitant to post there. Devs,  please move it where it belongs.**

**Describe the bug**

Alice communicates with Bob via Session. The "Disappearing messages timer" is set.
Alice has two devices, X and Y. Alice uses mostly X and only seldom Y.
Bob has only one device, Z.

Alice chats with Bob using X, respectively Z. The countdown for the disappearing messages starts as soon as they're read and, after a while, the messages disappear from X and Z (as intended).

Some time later (but within the 14-day period after the first message was exchanged), Alice powers on Y - and the expired messages are downloaded onto Y; the countdown starts anew on Y.

Expected behavior: expiration status should be kept on the Oxen network. Y should not download the messages that have been already read and disappeared,

Steps to reproduce the behavior.

1. Link multiple devices to the same conversation;
2. Set a disappearing messages timer;
3. Wait for messages to disappear on one device;
4. Turn on another device linked to the conversation.

**Comment by mpretty-cyro** [comment]
Closing this as #731 is now live and this issue was related to the legacy version. Feel free to open a new issue if you experience any problems like this with the updated version of Disappearing Messages
