### ISSUE TITLE
Messages fail to be sent

### ISSUE THREAD

**Issue by BeHooman** [oxen-io/session-ios#740]
Sometimes, at random, messages just won't get delivered. After the three dotted icon shows for a long while, the red icon shows up in its place signifying the message hasn't been delivered. This happens both with text messages and voice messages.

![image](https://user-images.githubusercontent.com/109044644/203347308-e2edbe41-60db-47ed-9095-ad59dc7cf7db.png)

**Comment by RyanRory** [comment]
Hi @BeHooman , thanks for reaching out. If you tap on the red `!`, there will be a popup showing the reason why the message is failed to send. If this issue happens to you next time, could you give us a screenshot of the failure reason? That would help us a lot debug this issue. Thanks in advance!

**Comment by KeeJef** [comment]
Yeah this seems to happen to me sometimes too, usually when i open the app after not having opened for a few hours

**Comment by KeeJef** [comment]
This has stopped occurring for me after updating to 2.2.5 and beyond, are you still seeing this @BeHooman ?
