### ISSUE TITLE
After exiting the program not receive any reminders for new messages

### ISSUE THREAD

**Issue by KWAN1210** [oxen-io/session-ios#741]
**Code of conduct**

- [ ok] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md).

**Describe the bug**
I am currently using the latest version of Sessoin on my ios device, but I find that every time I exit the program, I will not receive any reminders for new messages.A clear and concise description of what the bug is.

**To reproduce**

Steps to reproduce the behavior.

**Screenshots or logs**

If applicable, add screenshots or logs to help explain your problem.

**Smartphone (please complete the following information):**

 - Device: [e.g. iPhone 13pro]
 - OS: [e.g. iOS 16.1.1]
 - Version of Session or latest commit hash
2.2.3
**Additional context**
What's more, in view of the closed nature of ios devices, if the Apple store in a certain country removes the session, it will be difficult for ordinary users to download and install it. Is there any other way, such as downloading and installing sessions on iOS devices through some third-party channels?
Thanks, looking forward to reply.

**Comment by KeeJef** [comment]
Are you using Fast mode for the Session "Notification strategy"? you should be able to see under Settings -> Notifications inside Session

**Comment by KeeJef** [comment]
Closing because more information is required
