### ISSUE TITLE
Not fixing pod  issue in xcode 13.4

### ISSUE THREAD

**Issue by appleiOSdevelopr** [oxen-io/session-ios#747]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### iOS Version

swift 5 xcode 13.4

### Session Version

2.2.4

### Anything else?

<img width="619" alt="Screenshot 2022-12-01 at 5 13 50 PM" src="https://user-images.githubusercontent.com/45183020/205271847-6bd8c4fd-abe6-4bcb-84d9-e2efea36042e.png">

**Comment by appleiOSdevelopr** [comment]
@mpretty-cyro how to fix this issue ? Please

**Comment by mpretty-cyro** [comment]
> @mpretty-cyro how to fix this issue ? Please

I don’t know if I’ll have time to look into this further over the next couple of days but ‘Database+Schema’ is a file in GRDB (the database library we use)

The version [GRDB](https://github.com/groue/GRDB.swift) we are using requires Swift 5.7 which I believe came with XCode 14.0 so you might just need to update to the latest version of XCode to resolve the issue

**Comment by KeeJef** [comment]
Closing for now, please reopen if you continued to face this issue after upgrading the latest version of XCode
