### ISSUE TITLE
Auto delete bug

### ISSUE THREAD

**Issue by Henry-Lee8619** [oxen-io/session-ios#766]
there is a bug in auto delete messages because it only delete messages on device instead of in network. However, it’s normal when I deliberately delete one messages.
Besides, iOS can’t delete messages in public groups while android can delete messages. 
In addition, iOS can rename contact while android can’t rename contact.

**Comment by RyanRory** [comment]
Hi @Henry-Lee8619, thanks for your feedback!

> there is a bug in auto delete messages because it only delete messages on device instead of in network. However, it’s normal when I deliberately delete one messages.

We are rebuilding the whole disappearing messages in this PR #731, hope it can fix all the issues.

> Besides, iOS can’t delete messages in public groups while android can delete messages.

We are aware of this and will fix it to make it consistent across platforms.

> In addition, iOS can rename contact while android can’t rename contact.

We'll talk to the Android devs to see what we can do to make it consistent.

**Comment by mpretty-cyro** [comment]
Closing this as #731 is now live, feel free to open a new issue if you run into issues with the updated version of Disapeparing Messages
