### ISSUE TITLE
iOS push notification inconsistent 

### ISSUE THREAD

**Issue by Loki116777** [oxen-io/session-ios#776]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

iOS push notifications work on and off throughout the day with fast mode on. Used two different iPhones with latest update and both have the issue. Notifications mostly show only when app is open and feed refreshed. 

### Expected Behavior

When first downloaded the app this was not an issue. Received push notifications. Don’t know why it changed. Just giving feedback, from not just my iOS but a few others as well. 

### iOS Version

16.3

### Session Version

2.2.5 (390)

**Comment by GittyUpMyHorsey** [comment]
I am also experiencing this. iOS and the latest version of session.

**Comment by RyanRory** [comment]
Hi @Loki116777 @GittyUpMyHorsey, thanks for the feedback. We are aware of the issue and will update the push notification server soon to improve the stability.

**Comment by RyanRory** [comment]
Hi @GittyUpMyHorsey @Loki116777 , happy to report we've updated the push notification server and Session iOS for a better experience of push notifications. Can I have some feedback on how does the push notification work for you guys right now?

**Comment by Loki116777** [comment]
Hey! Every thing is working awesome. Thanks for the update!Sent from my iPhoneOn Feb 16, 2023, at 4:15 PM, RyanZhao ***@***.***> wrote:﻿
Hi @GittyUpMyHorsey @Loki116777 , happy to report we've updated the push notification server and Session iOS for a better experience of push notifications. Can I have some feedback on how does the push notification work for you guys right now?

**Comment by RyanRory** [comment]
Hi @Loki116777 , awesome to hear that. I'll close this issue now.
