### ISSUE TITLE
[BUG] Fatal crash every time, after updating to 2.2.10

### ISSUE THREAD

**Issue by mstroubadour** [oxen-io/session-ios#819]
Previously using 2.2.3 on an iOS 13.1.3 device fine. A few days ago, messages would no longer send, instead always got the red exclamation mark when attempting to send.

Upgraded to 2.2.10 to see if this would fix this, and now the app crashes a few seconds after attempting to launch, every time. It only shows the splash screen, gets no further.

Relevant crash report lines (I'm typing this in hence not including it all, let me know if you would like any other parts):

```
Parent process: launchd [1]
Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000, 0x0000
Exception Note: EXC_CORPSE_NOTIFY
Termination Description: DYLD, Assertion failed: (gotLocation), function applyFixupsToImage_block_invoke_3, 
file /BuildRoot/Library/Caches/com.apple.xbs/Sources/dyld/dyld-732.3/dyld/Loading.cpp, line 775
Highlighted by Thread: 0

Backtrace not available

```

### iOS Version

iOS 13.1.3

### Session Version

2.2.10

**Comment by KeeJef** [comment]
Would you be able to provide the full crash report to kee@oxen.io ?

**Comment by mstroubadour** [comment]
Sent, thanks!

**Comment by mpretty-cyro** [comment]
Have spent a bunch of time investigating this without much luck - the issue itself is that the OS is failing to load the dynamic libraries needed to run the app.

Annoyingly it seems that the latest version of XCode (14.3) doesn't allow us to target iOS 13 simulators and it's hard to source devices running iOS 13 so there isn't a good way for me to debug this issue properly - that being said it seems that others in the [Apple dev forums have run into what looks like the same issue](https://developer.apple.com/forums/thread/727611) and didn't have the problem when building using XCode 14.2

So the plan is to avoid using XCode 14.3 for release builds (which will hopefully prevent this from happening) we're looking to try and get the next release (`2.2.12`) out in the next couple of days

**Comment by fracting** [comment]
I can reproduce the crash at launch of Session iOS 2.2.10 (installed from .ipa file) with an `iPhone 11 Pro Max + iOS v13.3` from https://app-live.browserstack.com/

I can confirm Session iOS 2.2.4 (installed from .ipa file) does not crash with `iPhone 11 Pro Max + iOS v13.3` from browserstack.
(however it suffers a hang similar to https://github.com/oxen-io/session-android/issues/1106)

**Comment by fracting** [comment]
Update: Session iOS 2.2.12 (installed from .ipa file) doesn't crash anymore with `iPhone 11 Pro Max + iOS v13.3` from https://app-live.browserstack.com/

**Comment by mpretty-cyro** [comment]
> Update: Session iOS 2.2.12 (installed from .ipa file) doesn't crash anymore with `iPhone 11 Pro Max + iOS v13.3` from https://app-live.browserstack.com/

Thanks for confirming!

**Comment by mstroubadour** [comment]
2.2.12 is working here too, from the iOS app store. Big thanks for sorting this so fast!
