### ISSUE TITLE
[BUG] <title> Icon display for sent messages incorrect and shows pending 

### ISSUE THREAD

**Issue by ghost** [oxen-io/session-ios#829]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Within the main menu, sent messages display a three dot pending icon. 

### Expected Behavior

They should display a tick icon.

### Steps To Reproduce

Open your main menu.
See sent messages displaying incorrect icon.

### iOS Version

iOS 16.3.1

### Session Version

2.2.12

**Comment by fracting** [comment]
https://github.com/oxen-io/session-ios/pull/833

**Comment by fracting** [comment]
Fixed for me in Session iOS 2.2.13.

The original reporter deleted their account.

I think we can close this issue @mpretty-cyro @RyanRory 

Thanks for the great work!
