### ISSUE TITLE
Ephemeral messages

### ISSUE THREAD

**Issue by eligibleshield** [oxen-io/session-ios#860]
When will ephemeral messages be deleted from the swarm instead of just the client?

**Comment by mpretty-cyro** [comment]
Currently one-to-one and group conversations are removed from the swarm after 14 days, the Disappearing Messages feature is currently being rebuilt (https://github.com/oxen-io/session-ios/pull/731) and once that's merged in messages will be correctly removed from the swarm based on the disappearing messages setting

**Comment by mpretty-cyro** [comment]
> When will that be merged?

It's still in development but is currently planned to come after #751 is finalised, we can't give any specific dates around when it'll be completed at this stage

> What are configuration messages?

These are messages which are used to keep the user state consistent between devices (ie. so if you have the same account setup on multiple devices you have the same conversations and profile info)

**Comment by mpretty-cyro** [comment]
> So it isn't considered a priority?

The rebuilt feature is dependant on some changes included in the User Config feature (#751) which is currently going through a few rounds of internal testing and bug fixing so it can't come until that has been completed

Once User Config is sorted a couple of small changes are needed and then the updated Disappearing Messages (#731) needs to go through it's own testing so it's a bit hard to gauge dates as it depends on what comes up during testing

**Comment by mpretty-cyro** [comment]
#731 has now been released and is live across all platforms so messages sent with the new setting enabled will be removed from devices and the swarm at the same time
