### ISSUE TITLE
[BUG] Delete/Remove contacts does not work

### ISSUE THREAD

**Issue by featherridge** [oxen-io/session-ios#875]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was told by support I could swipe left to remove an old contact.
Swiping left does nothing.

### Expected Behavior

The ability to delete an old contact from the contact list permanently.

When swiping left on a contact, having the option to delete them.

### Steps To Reproduce

1. Contact list
2. Swipe left
3. Nothing happens 

### iOS Version

16.5.1

### Session Version

2.3.1 (420)

**Comment by mpretty-cyro** [comment]
Sorry the information you were provided is incorrect - currently there is no way to fully remove a contact, it is on the list to be added but will need to wait until after the onboarding work (#891) is completed as it includes changes to this area.

There is a separate feature request issue for this functionality (#866) so I will close this issue in favour of that one
