### ISSUE TITLE
[BUG] <title> ambiguous, unknown controls in system settings ->session panel

### ISSUE THREAD

**Issue by Whoisipo** [oxen-io/session-ios#885]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not labelled toggle switch and a slider, under a “Session settings” section “Group”.
Are they functional? What purpose do these serve?

### Steps To Reproduce

System settings
Session

### iOS Version

16.6

### Session Version

2.3.1 (420)

### Anything else?

![IMG_1730](https://github.com/oxen-io/session-ios/assets/141918749/7c799653-b1c1-4040-9d74-22531af663bf)

**Comment by mpretty-cyro** [comment]
This was unintentionally added by a debug commit that I forgot to remove, the settings don't do anything but they are replaced as part of #893

**Comment by Whoisipo** [comment]
Thank you, mpretty-cyro . I’m glad this issue has been resolved.
