### ISSUE TITLE
[BUG] <Tagging users via @username no longer works>

### ISSUE THREAD

**Issue by featherridge** [oxen-io/session-ios#931]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tagging username in a closed group does not work.

### Expected Behavior

Tagging username in a closed group works.

### Steps To Reproduce

1. In a closed group
2. Type @username
3. See usernames suggested to tag, except the one username you want to tag
4. Repeat

### iOS Version

iOS 16.7

### Session Version

2.4.3 (427)

**Comment by mpretty-cyro** [comment]
Jira ticket SES-1284

**Comment by mpretty-cyro** [comment]
On a couple of my test devices I was able to find a case there the FTS tables had stopped updating correctly which resulted in being able to search for some users and not others (I've added a migration to recreate any which are found to be invalid as part of #946)

Not 100% sure if this is the same issue you were running into but let me know if you still experience this issue once `2.4.5` comes out

**Comment by featherridge** [comment]
@mpretty-cyro noted. Thank you.

**Comment by mpretty-cyro** [comment]
@featherridge Are you still running into this issue?

**Comment by featherridge** [comment]
@mpretty-cyro no, this has been resolved. Thank you.
