### ISSUE TITLE
[BUG] <No notifications after forking>

### ISSUE THREAD

**Issue by noobinandroid** [oxen-io/session-ios#932]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

Im doing some small work on the source code, but when i change bundle ID, the notification on the background stop. I only get foreground notifications on calls and messages.

Any idea how this can be resolved?

### iOS Version

17.0

**Comment by KeeJef** [comment]
You will need to register your new bundle id with Apple to use push notifications
