### ISSUE TITLE
The issue encountered after upgrading to the latest version on the iOS mobile device

### ISSUE THREAD

**Issue by miss0588** [oxen-io/session-ios#972]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Whenever I try to open the latest version of the iOS app on my phone, it consistently fails to connect to the internet and keeps crashing. What could be the issue

**Comment by pottsandpans** [comment]
This is issue is being tracked internally on Jira: SES-1925

**Comment by mpretty-cyro** [comment]
This is related to the network updates that were included in `2.6.0`, please see https://github.com/oxen-io/session-ios/issues/975#issuecomment-2138377398 for more information

I'll close this as a duplicate but if you continue to experience issues once `2.6.1` feel free to re open
