### ISSUE TITLE
[BUG] <title>Network status  disconnected

### ISSUE THREAD

**Issue by mubali1987** [oxen-io/session-ios#978]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[com.loki-project.loki-messenger 2024-05-25--08-46-32-362.log](https://github.com/oxen-io/session-ios/files/15444949/com.loki-project.loki-messenger.2024-05-25--08-46-32-362.log)

### iOS Version

17.4.1

### Session Version

2.6

**Comment by mpretty-cyro** [comment]
This is most likely related to the network updates that were included in `2.6.0`, please see https://github.com/oxen-io/session-ios/issues/975#issuecomment-2138377398 for more information

I'll close this as a duplicate but if you continue to experience issues once `2.6.1` feel free to re open
