### ISSUE TITLE
The session on the IOS system has been unable to connect to the network

### ISSUE THREAD

**Issue by ShineYangGod** [oxen-io/session-ios#979]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The session on the IOS system has been unable to connect to the network，Path cannot be loaded

### Expected Behavior

Normal network connection, normal loading of paths

### Steps To Reproduce

Open the iOS side and log in to the session normally, but the path cannot be loaded.

### iOS Version

17.5.1

### Session Version

2.6.0

**Comment by mpretty-cyro** [comment]
This is most likely related to the network updates that were included in `2.6.0`, please see https://github.com/oxen-io/session-ios/issues/975#issuecomment-2138377398 for more information

I'll close this as a duplicate but if you continue to experience issues once `2.6.1` feel free to re open
