### ISSUE TITLE
[BUG] Cannot send URL message

### ISSUE THREAD

**Issue by PYU224** [oxen-io/session-ios#989]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I had sent message and URL, Session could not send my message and URL.

### iOS Version

iOS 17.5.1

### Session Version

2.6.2

**Comment by KeeJef** [comment]
Hey @PYU224 is this fixed in the latest iOS version 2.6.3? We fixed a number of issues with attachments, and behind the scenes link previews rely on attachments to work properly. Please comment on this issue if it wasn't fixed for you on the latest version

**Comment by PYU224** [comment]
My Session Version is 2.6.3.

**Comment by PYU224** [comment]
Thanks.
I try sending message with URL.

**Comment by PYU224** [comment]
I can send a message with URL in Session chat now.
Thanks.
