### ISSUE TITLE
[BUG] I was kicked out of an open group and can't rejoin.

### ISSUE THREAD

**Issue by PYU224** [oxen-io/session-ios#993]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After syncing with the desktop version, I get kicked out of the open group and can't rejoin.

**Comment by pottsandpans** [comment]
Can you please provide us with some logs for this so we can investigate it further?

**Comment by PYU224** [comment]
Okay, where can I see the log?

**Comment by KeeJef** [comment]
in the Session app, go to  Settings -> Help -> Export Logs

**Comment by PYU224** [comment]
Now I can join the open group from the URL.
I apologize to you for a fuss over.

**Comment by KeeJef** [comment]
Ok great, ill close this issue for now
