### ISSUE TITLE
[BUG] Session iOS App crashes shortly after opening (iOS 14.8)

### ISSUE THREAD

**Issue by xXG0DLessXx** [oxen-io/session-ios#999]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-ios/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the latest Session version available in the AppStore (2.7.0), the app crashes shortly after opening. Attached here should be a short video depicting the issue and the iOS crash log.

https://github.com/user-attachments/assets/60f6105c-7bb1-4730-9d00-ce8b5e75c6c0

[Session-2024-08-13-180038.txt](https://github.com/user-attachments/files/16639747/Session-2024-08-13-180038.txt)

### Expected Behavior

The app should not crash, or you should clearly state that the lower iOS versions are no longer supported.

### Steps To Reproduce

1. Be on iOS 14.8 (iPhone SE Gen1).
2. Update to the latest version of Session from the AppStore
3. Open the app.

### iOS Version

iOS 14.8

### Session Version

2.7.0

**Comment by mpretty-cyro** [comment]
Hi @xXG0DLessXx, we released iOS version `2.7.1` over the weekend which _should_ fix this issue - can you please try to install and let us know if you still experience the issue?

Just to note - `2.7.1` is currently slowly rolling out to users so may not have automatically updated for you (you can manually trigger the update via the Session page on the AppStore: https://apps.apple.com/us/app/session-private-messenger/id1470168868)

**Comment by xXG0DLessXx** [comment]
Hello, the latest update seems good. No longer crashes on my iPhone SE (Gen1) on iOS 14.8. Thx for fixing this quickly!

**Comment by mpretty-cyro** [comment]
Awesome, thanks for confirming it's fixed 🙏
